



CREATE OR REPLACE TABLE EMP(EMP_ID NUMBER)
CLUSTER BY (EMP_ID);



SELECT SYSTEM$CLUSTERING_INFORMATION('EMP');



SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS inner JOIN  SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER
LIMIT 1000;

SELECT CURRENT_ROLE();

SHOW PARAMETERS LIKE
'CORTEX_CODE_SNOWSIGHT_DAILY_EST_CREDIT_LIMIT_PER_USER'
IN ACCOUNT;

SHOW PARAMETERS LIKE
'CORTEX_CODE_SNOWSIGHT_DAILY_EST_CREDIT_LIMIT_PER_USER'
IN USER;